---
name: Lab 3 Feature Requests
about: Add a feature to satisfy each requirement in Lab 3
title: "[FEATURES]"
labels: enhancement
assignees: AndrewLe0427

---

*Name*: Add Standup Meeting md File

*Description*: Add standup.md file to represent stand up meeting notes

*Due Date*: 4/21/26 11:59pm
